
# ---standard pioneer footprint---
# ---(in meters)---
# footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
# footprint: [ [-1.5,-0.425], [1.5,-0.425], [1.5,0.425], [-1.5,0.425] ]
footprint: [ [-1.7,-0.7], [1.7,-0.7], [1.7,0.7], [-1.7,0.7] ]

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 30.0
 raytrace_range: 35
 inflation_radius: 0.5
 track_unknown_space: false
 combination_method: 1

 observation_sources: base_scan
 base_scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     10  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
